---
  api_key:
    description: "Palo Alto API key"
    type: "string"
    required: true
  tag:
    description: "Palo Alto object tag"
    type: "string"
    required: true  
  ips:
    description: "IP addresses"
    type: "string"
    required: true
  url:
    description: "API Urls"
    type: "string"
    required: true